### PR TITLE
Fixed issue #1 and #4

### PR DESCRIPTION
**Pull request by vibharaj**
The intro snippet is now automatically visible after parsing the job description and the job description can be displayed if the user clicks on the description panel as an accordion.

### CODE REVIEW

**Comment by mattcheah** [comment]
Hey Vibha, It's looking good. 
I do think the grey 'job description' bar stands out a little too much, what if you added another button in the same flex container as the "Enter New Job Description" button, and had that toggle the visibility of the accordion? 
Something like this: 
image

Then you can keep the grey bar when the job description is showing (With a title like "Parsed Job Description" or something like that) and hide it when the accordion is closed? What do you think about that?

**Comment by vibharaj** [comment]
Hi, I just made those changes and checked it in. Please review and let me know. Thanks!

**Comment by mattcheah** [comment]
Would you mind making one last change for me? When the parsed job description is _visible_, can you change the text on the button to "Hide Job Description"? so it changes every time you toggle it on and off? 

If you get that to me tomorrow I'll merge. Thanks Vibha.

**Comment by vibharaj** [comment]
Sure! Will make the change and let you know. Thanks.

**Comment by mattcheah** [comment]
Looks great!

**Comment by mattcheah** [comment]
Merged and published a new NPM version! For the package.json file I can add
your Name, Email, and/or Github repo as a contributor. Would you like me to
add all of those for you?

**Comment by vibharaj** [comment]
Sure, Thanks a lot! 
Thank you for all your help. Appreciate your time. Working on this project was a great learning experience for me. Thank you so much!

**Pull request merged**
