### PR TITLE
added button to show all categories in the user's collection

### PR DESCRIPTION
**Pull request by treventrujillo**
Added table under results table to show all unlisted categories. Modified pipe to return unlisted categories if passed argument.

### CODE REVIEW

**Comment by mattcheah** [comment]
Appending extra categories to the table could look like this:
show more categories

**Comment by treventrujillo** [comment]
Yes that makes perfect sense, thank you for letting me know. I will get to work on these changes.

**Comment by treventrujillo** [comment]
I'm a little new to pull requests and proper use of them. Would you like me to close this pull request and open another when I have completed the changes or is there a way to add commits to a pull request? Thanks for your help in this too.

**Comment by mattcheah** [comment]
Since you're merging your master branch https://github.com/treventrujillo/cover-letter-snippets, you just make your commits the way you've already been doing it and I should be able to see the updates here I think. Let me know when you're done, thanks!

**Comment by treventrujillo** [comment]
I added the requested changes and built it up with ng build --prod.

**Comment by mattcheah** [comment]
Issues #2 (https://github.com/mattcheah/cover-letter-snippets/issues/2) fixed

**Pull request merged**
